language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - 11
os: linux
cache:
  yarn: true
install:
  - |
    yarn install
script:
  - |
    yarn test
after_success:
  - |
    cat ./coverage/lcov.info | ./node_modules/.bin/codecov